create a dictionary

In [1]:
import pandas as pd

In [2]:
d={'movie':['KGF','pushpa','kuberaa','peddi','yuvaratna','sanam teri kasam','3 idiots','bahubali','RRR','pailwaan'],
   'rating':[9.5,9.2,None,8.5,8.0,7.5,None,9.7,9.6,8.9],
   'language-year':['Kannada-2018','Telugu-2021','Tamil-2022','Telugu-2026','Kannada-2009','Hindi-2016','Hindi-2009','Telugu-2015','Telugu-2022','Kannada-2019'],
   'cast':[['Yash','Srinidhi Shetty'],['Allu Arjun','Rashmika'],['Dhanush','Sunaina'],['Ram Charan','Jhanvi Kapoor'],['Puneeth Rajkumar','Sayyeshaa'],['Harshvardhan Rane','Mawra'],['Aamir Khan','Kareena Kapoor'],['Prabhas','Anushka'],['NTR Jr.','Alia'],['Sudeep','Akanksha Singh']],
   'Hotstar':['1','1','1','0','0','1','0','1','1','0'],
   'Netflix':['No','Yes','Yes','No','Yes','Yes','Yes','No','Yes','No']
   }

DataFrame->Table

Series->column

In [3]:
df=pd.DataFrame(d)
df

,movie,rating,language-year,cast,Hotstar,Netflix
0,KGF,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,No
1,pushpa,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,Yes
2,kuberaa,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,Yes
3,peddi,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,No
4,yuvaratna,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,Yes
5,sanam teri kasam,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,Yes
6,3 idiots,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,Yes
7,bahubali,9.7,Telugu-2015,"[Prabhas, Anushka]",1,No
8,RRR,9.6,Telugu-2022,"[NTR Jr., Alia]",1,Yes
9,pailwaan,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,No

## head()

In [4]:
#displays first 5 records
#we can assign any number inside head to display no of records
df.head()

,movie,rating,language-year,cast,Hotstar,Netflix
0,KGF,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,No
1,pushpa,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,Yes
2,kuberaa,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,Yes
3,peddi,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,No
4,yuvaratna,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,Yes

## tail()

In [5]:
#display last 5 records
df.tail()

,movie,rating,language-year,cast,Hotstar,Netflix
5,sanam teri kasam,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,Yes
6,3 idiots,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,Yes
7,bahubali,9.7,Telugu-2015,"[Prabhas, Anushka]",1,No
8,RRR,9.6,Telugu-2022,"[NTR Jr., Alia]",1,Yes
9,pailwaan,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,No

## info()

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie          10 non-null     str
 1   rating         8 non-null      float64
 2   language-year  10 non-null     str
 3   cast           10 non-null     object
 4   Hotstar        10 non-null     str
 5   Netflix        10 non-null     str
dtypes: float64(1), object(1), str(4)
memory usage: 831.0+ bytes

If null values present in any column ,then it's datatype shows as float

If there are no null values,then it will be int

In [7]:
#dataframe_name[col_name]-> used to dispaly particular column
df['movie']

0                 KGF
1              pushpa
2             kuberaa
3               peddi
4           yuvaratna
5    sanam teri kasam
6            3 idiots
7            bahubali
8                 RRR
9            pailwaan
Name: movie, dtype: str

In [8]:
#dataframe_name[[col_name,col_name]]-> to select multiple columns
df[['movie','rating']]

              movie  rating
0               KGF     9.5
1            pushpa     9.2
2           kuberaa     NaN
3             peddi     8.5
4         yuvaratna     8.0
5  sanam teri kasam     7.5
6          3 idiots     NaN
7          bahubali     9.7
8               RRR     9.6
9          pailwaan     8.9

In [9]:
#dataframe_name[colname==row](2D)-> to select column as well as row
df[df['movie']=='KGF']

  movie  rating language-year                     cast Hotstar Netflix
0   KGF     9.5  Kannada-2018  [Yash, Srinidhi Shetty]       1      No

## title()

In [10]:
df['movies']=df['movie'].str.title()
df

,movie,rating,language-year,cast,Hotstar,Netflix,movies
0,KGF,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,No,Kgf
1,pushpa,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,Yes,Pushpa
2,kuberaa,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,Yes,Kuberaa
3,peddi,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,No,Peddi
4,yuvaratna,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,Yes,Yuvaratna
5,sanam teri kasam,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,Yes,Sanam Teri Kasam
6,3 idiots,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,Yes,3 Idiots
7,bahubali,9.7,Telugu-2015,"[Prabhas, Anushka]",1,No,Bahubali
8,RRR,9.6,Telugu-2022,"[NTR Jr., Alia]",1,Yes,Rrr
9,pailwaan,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,No,Pailwaan

## drop()

In [11]:
#drop-> used to delete the columns
df=df.drop(columns=['movie'])

In [12]:
df

,rating,language-year,cast,Hotstar,Netflix,movies
0,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,No,Kgf
1,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,Yes,Pushpa
2,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,Yes,Kuberaa
3,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,No,Peddi
4,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,Yes,Yuvaratna
5,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,Yes,Sanam Teri Kasam
6,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,Yes,3 Idiots
7,9.7,Telugu-2015,"[Prabhas, Anushka]",1,No,Bahubali
8,9.6,Telugu-2022,"[NTR Jr., Alia]",1,Yes,Rrr
9,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,No,Pailwaan

## replace()

In [13]:
df=df.replace({'Yes':1,'No':0})
df

,rating,language-year,cast,Hotstar,Netflix,movies
0,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,0,Kgf
1,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,1,Pushpa
2,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,1,Kuberaa
3,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi
4,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna
5,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam
6,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots
7,9.7,Telugu-2015,"[Prabhas, Anushka]",1,0,Bahubali
8,9.6,Telugu-2022,"[NTR Jr., Alia]",1,1,Rrr
9,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,0,Pailwaan

In [14]:
df['language-year']=df['language-year'].str.title()

In [15]:
df

,rating,language-year,cast,Hotstar,Netflix,movies
0,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,0,Kgf
1,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,1,Pushpa
2,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,1,Kuberaa
3,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi
4,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna
5,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam
6,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots
7,9.7,Telugu-2015,"[Prabhas, Anushka]",1,0,Bahubali
8,9.6,Telugu-2022,"[NTR Jr., Alia]",1,1,Rrr
9,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,0,Pailwaan

## split()

In [16]:
df[['Language','Year']]=df['language-year'].str.split('-',expand=True)
df

,rating,language-year,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,Kannada-2018,"[Yash, Srinidhi Shetty]",1,0,Kgf,Kannada,2018
1,9.2,Telugu-2021,"[Allu Arjun, Rashmika]",1,1,Pushpa,Telugu,2021
2,NaN,Tamil-2022,"[Dhanush, Sunaina]",1,1,Kuberaa,Tamil,2022
3,8.5,Telugu-2026,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi,Telugu,2026
4,8.0,Kannada-2009,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009
5,7.5,Hindi-2016,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam,Hindi,2016
6,NaN,Hindi-2009,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots,Hindi,2009
7,9.7,Telugu-2015,"[Prabhas, Anushka]",1,0,Bahubali,Telugu,2015
8,9.6,Telugu-2022,"[NTR Jr., Alia]",1,1,Rrr,Telugu,2022
9,8.9,Kannada-2019,"[Sudeep, Akanksha Singh]",0,0,Pailwaan,Kannada,2019

In [17]:
df=df.drop(columns=['language-year'])
df

,rating,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,"[Yash, Srinidhi Shetty]",1,0,Kgf,Kannada,2018
1,9.2,"[Allu Arjun, Rashmika]",1,1,Pushpa,Telugu,2021
2,NaN,"[Dhanush, Sunaina]",1,1,Kuberaa,Tamil,2022
3,8.5,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi,Telugu,2026
4,8.0,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009
5,7.5,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam,Hindi,2016
6,NaN,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots,Hindi,2009
7,9.7,"[Prabhas, Anushka]",1,0,Bahubali,Telugu,2015
8,9.6,"[NTR Jr., Alia]",1,1,Rrr,Telugu,2022
9,8.9,"[Sudeep, Akanksha Singh]",0,0,Pailwaan,Kannada,2019

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    8 non-null      float64
 1   cast      10 non-null     object
 2   Hotstar   10 non-null     str
 3   Netflix   10 non-null     object
 4   movies    10 non-null     str
 5   Language  10 non-null     str
 6   Year      10 non-null     str
dtypes: float64(1), object(2), str(4)
memory usage: 877.0+ bytes

## astype()

In [19]:
df=df.astype({'Year':'int'})
df

,rating,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,"[Yash, Srinidhi Shetty]",1,0,Kgf,Kannada,2018
1,9.2,"[Allu Arjun, Rashmika]",1,1,Pushpa,Telugu,2021
2,NaN,"[Dhanush, Sunaina]",1,1,Kuberaa,Tamil,2022
3,8.5,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi,Telugu,2026
4,8.0,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009
5,7.5,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam,Hindi,2016
6,NaN,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots,Hindi,2009
7,9.7,"[Prabhas, Anushka]",1,0,Bahubali,Telugu,2015
8,9.6,"[NTR Jr., Alia]",1,1,Rrr,Telugu,2022
9,8.9,"[Sudeep, Akanksha Singh]",0,0,Pailwaan,Kannada,2019

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    8 non-null      float64
 1   cast      10 non-null     object
 2   Hotstar   10 non-null     str
 3   Netflix   10 non-null     object
 4   movies    10 non-null     str
 5   Language  10 non-null     str
 6   Year      10 non-null     int64
dtypes: float64(1), int64(1), object(2), str(3)
memory usage: 837.0+ bytes

loc[]->used for selecting row as well as column

loc[row_based(mandatory),col_based(optional)]

## loc[]

In [21]:
df.loc[1]

rating                         9.2
cast        [Allu Arjun, Rashmika]
Hotstar                          1
Netflix                          1
movies                      Pushpa
Language                    Telugu
Year                          2021
Name: 1, dtype: object

In [22]:
#to select multiple records
df.loc[[0,3,5]]

,rating,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,"[Yash, Srinidhi Shetty]",1,0,Kgf,Kannada,2018
3,8.5,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi,Telugu,2026
5,7.5,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam,Hindi,2016

In [23]:
df.loc[[0,3,5],['movies']]

             movies
0               Kgf
3             Peddi
5  Sanam Teri Kasam

In [24]:
#when we pass miultiple values we must enclose in a square bracket
df.loc[[0,3,5],['movies','rating']]

             movies  rating
0               Kgf     9.5
3             Peddi     8.5
5  Sanam Teri Kasam     7.5

## loc[] using and function

In [25]:
df[(df['Language']=='Kannada') & (df['Netflix']==1)]

,rating,cast,Hotstar,Netflix,movies,Language,Year
4,8.0,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009

In [26]:
df.loc[(df['Language']=='Kannada') & (df['Netflix']==1)]

,rating,cast,Hotstar,Netflix,movies,Language,Year
4,8.0,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009

## loc[] using or function

In [27]:
df.loc[(df['Year']==2018) | (df['Year']==2022)]

   rating                     cast Hotstar Netflix   movies Language  Year
0     9.5  [Yash, Srinidhi Shetty]       1       0      Kgf  Kannada  2018
2     NaN       [Dhanush, Sunaina]       1       1  Kuberaa    Tamil  2022
8     9.6          [NTR Jr., Alia]       1       1      Rrr   Telugu  2022

In [28]:
df.loc[((df['Year']==2018) | (df['Year']==2022)) & (df['Hotstar']==1)]

Empty DataFrame
Columns: [rating, cast, Hotstar, Netflix, movies, Language, Year]
Index: []

## fillna()

In [29]:
df=df.fillna(1)
df

,rating,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,"[Yash, Srinidhi Shetty]",1,0,Kgf,Kannada,2018
1,9.2,"[Allu Arjun, Rashmika]",1,1,Pushpa,Telugu,2021
2,1.0,"[Dhanush, Sunaina]",1,1,Kuberaa,Tamil,2022
3,8.5,"[Ram Charan, Jhanvi Kapoor]",0,0,Peddi,Telugu,2026
4,8.0,"[Puneeth Rajkumar, Sayyeshaa]",0,1,Yuvaratna,Kannada,2009
5,7.5,"[Harshvardhan Rane, Mawra]",1,1,Sanam Teri Kasam,Hindi,2016
6,1.0,"[Aamir Khan, Kareena Kapoor]",0,1,3 Idiots,Hindi,2009
7,9.7,"[Prabhas, Anushka]",1,0,Bahubali,Telugu,2015
8,9.6,"[NTR Jr., Alia]",1,1,Rrr,Telugu,2022
9,8.9,"[Sudeep, Akanksha Singh]",0,0,Pailwaan,Kannada,2019

## convert to csv file

In [30]:
df.to_csv('m1.csv',index=False)

## convert to excel file

In [31]:
df.to_excel('m2.xlsx')

## astype()

In [32]:
df=df.astype({'cast':'str'})

In [33]:
df['cast']=df['cast'].astype(str)

## strip()

In [34]:
df['cast']=df['cast'].str.strip('[]')

## replace()

In [35]:
df['cast']=df['cast'].str.replace(', ','-')

In [36]:
df['cast']=df['cast'].str.replace("'"," ")

In [37]:
df['cast']

0           Yash - Srinidhi Shetty
1            Allu Arjun - Rashmika
2                Dhanush - Sunaina
3       Ram Charan - Jhanvi Kapoor
4     Puneeth Rajkumar - Sayyeshaa
5        Harshvardhan Rane - Mawra
6      Aamir Khan - Kareena Kapoor
7                Prabhas - Anushka
8                   NTR Jr. - Alia
9          Sudeep - Akanksha Singh
Name: cast, dtype: str

In [38]:
df

,rating,cast,Hotstar,Netflix,movies,Language,Year
0,9.5,Yash - Srinidhi Shetty,1,0,Kgf,Kannada,2018
1,9.2,Allu Arjun - Rashmika,1,1,Pushpa,Telugu,2021
2,1.0,Dhanush - Sunaina,1,1,Kuberaa,Tamil,2022
3,8.5,Ram Charan - Jhanvi Kapoor,0,0,Peddi,Telugu,2026
4,8.0,Puneeth Rajkumar - Sayyeshaa,0,1,Yuvaratna,Kannada,2009
5,7.5,Harshvardhan Rane - Mawra,1,1,Sanam Teri Kasam,Hindi,2016
6,1.0,Aamir Khan - Kareena Kapoor,0,1,3 Idiots,Hindi,2009
7,9.7,Prabhas - Anushka,1,0,Bahubali,Telugu,2015
8,9.6,NTR Jr. - Alia,1,1,Rrr,Telugu,2022
9,8.9,Sudeep - Akanksha Singh,0,0,Pailwaan,Kannada,2019

## melt()

melt()->used to convert the column into row

In [39]:
pd.melt(df,value_vars=['Hotstar','Netflix'])

   variable value
0   Hotstar     1
1   Hotstar     1
2   Hotstar     1
3   Hotstar     0
4   Hotstar     0
5   Hotstar     1
6   Hotstar     0
7   Hotstar     1
8   Hotstar     1
9   Hotstar     0
10  Netflix     0
11  Netflix     1
12  Netflix     1
13  Netflix     0
14  Netflix     1
15  Netflix     1
16  Netflix     1
17  Netflix     0
18  Netflix     1
19  Netflix     0

In [40]:
pd.melt(df,value_vars=['Hotstar','Netflix'],var_name='OTT',value_name='Available')

        OTT Available
0   Hotstar         1
1   Hotstar         1
2   Hotstar         1
3   Hotstar         0
4   Hotstar         0
5   Hotstar         1
6   Hotstar         0
7   Hotstar         1
8   Hotstar         1
9   Hotstar         0
10  Netflix         0
11  Netflix         1
12  Netflix         1
13  Netflix         0
14  Netflix         1
15  Netflix         1
16  Netflix         1
17  Netflix         0
18  Netflix         1
19  Netflix         0

In [41]:
df1=pd.melt(df,id_vars=['movies','rating'],value_vars=['Hotstar','Netflix'],var_name='OTT',value_name='Available')

In [42]:
df1

              movies  rating      OTT Available
0                Kgf     9.5  Hotstar         1
1             Pushpa     9.2  Hotstar         1
2            Kuberaa     1.0  Hotstar         1
3              Peddi     8.5  Hotstar         0
4          Yuvaratna     8.0  Hotstar         0
5   Sanam Teri Kasam     7.5  Hotstar         1
6           3 Idiots     1.0  Hotstar         0
7           Bahubali     9.7  Hotstar         1
8                Rrr     9.6  Hotstar         1
9           Pailwaan     8.9  Hotstar         0
10               Kgf     9.5  Netflix         0
11            Pushpa     9.2  Netflix         1
12           Kuberaa     1.0  Netflix         1
13             Peddi     8.5  Netflix         0
14         Yuvaratna     8.0  Netflix         1
15  Sanam Teri Kasam     7.5  Netflix         1
16          3 Idiots     1.0  Netflix         1
17          Bahubali     9.7  Netflix         0
18               Rrr     9.6  Netflix         1
19          Pailwaan     8.9  Netflix         0

In [43]:
df1=df1.loc[df1['Available']==1]

In [44]:
df1

              movies  rating      OTT Available
11            Pushpa     9.2  Netflix         1
12           Kuberaa     1.0  Netflix         1
14         Yuvaratna     8.0  Netflix         1
15  Sanam Teri Kasam     7.5  Netflix         1
16          3 Idiots     1.0  Netflix         1
18               Rrr     9.6  Netflix         1

drop()

In [45]:
df1=df1.drop(columns=['Available'])

reset_index()

In [46]:
df1=df1.reset_index(drop=True)

In [47]:
df1

             movies  rating      OTT
0            Pushpa     9.2  Netflix
1           Kuberaa     1.0  Netflix
2         Yuvaratna     8.0  Netflix
3  Sanam Teri Kasam     7.5  Netflix
4          3 Idiots     1.0  Netflix
5               Rrr     9.6  Netflix

In [48]:
df['Hotstar']=df['Hotstar'].astype(int)

In [49]:
df['Netflix']=df['Netflix'].astype(int)

In [50]:
df['Total_platforms']=df['Hotstar']+df['Netflix']

In [51]:
df

,rating,cast,Hotstar,Netflix,movies,Language,Year,Total_platforms
0,9.5,Yash - Srinidhi Shetty,1,0,Kgf,Kannada,2018,1
1,9.2,Allu Arjun - Rashmika,1,1,Pushpa,Telugu,2021,2
2,1.0,Dhanush - Sunaina,1,1,Kuberaa,Tamil,2022,2
3,8.5,Ram Charan - Jhanvi Kapoor,0,0,Peddi,Telugu,2026,0
4,8.0,Puneeth Rajkumar - Sayyeshaa,0,1,Yuvaratna,Kannada,2009,1
5,7.5,Harshvardhan Rane - Mawra,1,1,Sanam Teri Kasam,Hindi,2016,2
6,1.0,Aamir Khan - Kareena Kapoor,0,1,3 Idiots,Hindi,2009,1
7,9.7,Prabhas - Anushka,1,0,Bahubali,Telugu,2015,1
8,9.6,NTR Jr. - Alia,1,1,Rrr,Telugu,2022,2
9,8.9,Sudeep - Akanksha Singh,0,0,Pailwaan,Kannada,2019,0

## Aggregate Functions

In [ ]:
#1.sum
#2.avg
#3.min
#4.count
#5.max

In [53]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   movies  6 non-null      str
 1   rating  6 non-null      float64
 2   OTT     6 non-null      str
dtypes: float64(1), str(2)
memory usage: 369.0 bytes

In [54]:
df1['rating'].count()

np.int64(6)

In [55]:
df1['rating'].agg(['min','max','mean','count'])

min      1.00
max      9.60
mean     6.05
count    6.00
Name: rating, dtype: float64

In [56]:
df1.agg({'rating':'min','movies':'count'})

rating    1.0
movies    6.0
dtype: float64

In [57]:
df1.agg({'rating':['min','mean'],'movies':'count'})

       rating  movies
min      1.00     NaN
mean     6.05     NaN
count     NaN     6.0

## Group By

In [58]:
df1.groupby('OTT')

In [59]:
df1

             movies  rating      OTT
0            Pushpa     9.2  Netflix
1           Kuberaa     1.0  Netflix
2         Yuvaratna     8.0  Netflix
3  Sanam Teri Kasam     7.5  Netflix
4          3 Idiots     1.0  Netflix
5               Rrr     9.6  Netflix

In [60]:
df1.groupby('OTT').agg({'rating':'mean'})

         rating
OTT
Netflix    6.05

AnalyticsWorld-1
download all notes
in dataset -->Titanic